# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.1
language: objective-c
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
  matrix:
    - TEST_TYPE=iOS
    - TEST_TYPE=CocoaPods
    - TEST_TYPE=Package
cache: cocoapods
podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# install:
# - |
#   bundle install
#   pod repo update --silent
#   pod install
script:
- |
  if [ "$TEST_TYPE" = iOS ]; then
    set -o pipefail
    xcodebuild test -workspace Example/CPMenuView.xcworkspace -sdk iphonesimulator -scheme CPMenuView_Example -configuration Debug -destination "platform=iOS Simulator,name=iPhone 6" -destination "platform=iOS Simulator,name=iPhone 6 Plus" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty
  elif [ "$TEST_TYPE" = CocoaPods ]; then
    pod lib lint --use-libraries CPMenuView.podspec
  fi